// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehmgjgrekjoaohnnlfmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobWdqZ3Jla2pvYW9obm5sZm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1MzI5NTAsImV4cCI6MjA4MzEwODk1MH0.2tI0RYA0IVBaIHpsL50RH_GAxu_K8aJDuodvcXSHtGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});